[package]
name = "uptime"
version = "0.0.1"
authors = []
build = "../../mkmain.rs"

[lib]
name = "uu_uptime"
path = "uptime.rs"

[dependencies]
getopts = "0.2.14"

[dependencies.uucore]
path = "../uucore"
features = ["utmpx"]

[[bin]]
name = "uptime"
path = "../../uumain.rs"
